CREATE DATABASE DuAn1_QuanLyBanQuanAo1
GO
USE DuAn1_QuanLyBanQuanAo1
GO


CREATE TABLE NHANVIEN(
	MaNV VARCHAR(10) NOT NULL,
	TenNV NVARCHAR(30) NOT NULL,
	DiaChi NVARCHAR(50) NOT NULL,
	GioiTinh BIT DEFAULT 1 NOT NULL,
	Email VARCHAR(30) NOT NULL,
	SoDienThoai VARCHAR(12) NOT NULL,
	NgaySinh DATE NOT NULL,
	VaiTro BIT DEFAULT 1 NOT NULL,
	MatKhau VARCHAR(15) NOT NULL, 
	TrangThai BIT DEFAULT 1 NOT NULL


	PRIMARY KEY(MaNV)
)

INSERT INTO NHANVIEN 
VALUES ('admin', N'Quản lý', N'HN', DEFAULT, 'abc@gmail.com','0385606568', '2021-01-01', DEFAULT, '123', DEFAULT)

CREATE TABLE KHACHHANG(
	MaKH INT IDENTITY(1, 1),
	TenKH NVARCHAR(30) NOT NULL,
	NgaySinh DATE,
	GioiTinh BIT DEFAULT 1 NOT NULL,
	SoDienThoai VARCHAR(12) NOT NULL,
	DiaChi NVARCHAR(50),
	TrangThai BIT DEFAULT 1 NOT NULL

	PRIMARY KEY(MaKH)
)


CREATE TABLE HINHTHUCTHANHTOAN(
	MaHTTT INT IDENTITY(1, 1)NOT NULL,
	TenHTTT NVARCHAR(30) NOT NULL,
	TrangThai BIT DEFAULT 1 NOT NULL

	PRIMARY KEY(MaHTTT)
)

CREATE TABLE SANPHAM(
	MaSP INT IDENTITY(1, 1) NOT NULL,
	TenSp nvarchar(50) NOT NULL,
	TrangThai BIT DEFAULT 1 NOT NULL

	PRIMARY KEY(MaSP)
)



CREATE TABLE LOAISP(
	MaLoai INT IDENTITY(1, 1)NOT NULL,
	TenLoai NVARCHAR(30) NOT NULL,
	TrangThai BIT DEFAULT 1 NOT NULL

	PRIMARY KEY(MaLoai)
   
)


CREATE TABLE MAUSAC(
	MaMauSac int IDENTITY(1, 1) NOT NULL,
	TenMauSac NVARCHAR(15) NOT NULL,
	TrangThai BIT DEFAULT 1 NOT NULL

	PRIMARY KEY(MaMauSac)
)

CREATE TABLE CHATLIEU(
	MaChatLieu INT IDENTITY(1, 1) NOT NULL,
	TenChatLieu NVARCHAR(15) NOT NULL,
	TrangThai BIT DEFAULT 1 NOT NULL
	
	PRIMARY KEY(MaChatLieu)
)


CREATE TABLE KICHTHUOC(
	MaKichThuoc INT IDENTITY(1, 1) NOT NULL,
	KichThuoc VARCHAR(15) NOT NULL,
	TrangThai BIT DEFAULT 1 NOT NULL

	PRIMARY KEY(MaKichThuoc)
)


CREATE TABLE CHITIETSANPHAM(
	MaCTSP INT IDENTITY(1,1),
	MaSP INT NOT NULL,
	MaLoai INT NOT NULL,
	MaMauSac int NOT NULL,
	MaKichThuoc INT NOT NULL,
	MaChatLieu INT NOT NULL,
	SoLuong INT NOT NULL,
	Gia FLOAT NOT NULL,
	GiamGia FLOAT NULL,
	TrangThai BIT DEFAULT 1

	PRIMARY KEY(MaCTSP)
	FOREIGN KEY(MaSP) REFERENCES SanPham(MaSP),
	FOREIGN KEY(MaMauSac) REFERENCES dbo.MAUSAC(MaMauSac),
	FOREIGN KEY(MaChatLieu) REFERENCES dbo.CHATLIEU(MaChatLieu),
	FOREIGN KEY(MaKichThuoc) REFERENCES dbo.KICHTHUOC(MaKichThuoc),
	FOREIGN KEY(MaLoai) REFERENCES dbo.LOAISP(MaLoai)
)


CREATE TABLE HOADON(
	MaHD INT IDENTITY(1375328, 1) NOT NULL,
	MaKH INT NOT NULL,
	MaNV VARCHAR(10) NOT NULL,	
	MaHTTT INT NOT NULL,
	NgayKhoiTao DATE DEFAULT(GETDATE() ) NOT NULL,
	TrangThai BIT DEFAULT 1 NOT NULL

	PRIMARY KEY(MaHD)
	FOREIGN KEY(MaKH) REFERENCES dbo.KHACHHANG(MaKH),
	FOREIGN KEY(MaNV) REFERENCES dbo.NHANVIEN(MaNV),
	FOREIGN KEY(MaHTTT) REFERENCES dbo.HINHTHUCTHANHTOAN(MaHTTT)
)


CREATE TABLE HOADONCHITIET(
	MaHDCT INT IDENTITY(1, 1),
	MaHD INT NOT NULL,
	MaCTSP INT NOT NULL,
	SoLuong INT NOT NULL,
	Gia FLOAT NOT NULL,
	GiamGia FLOAT NULL,
	ThanhTien FLOAT NOT NULL,
	TrangThai BIT DEFAULT 1 NOT NULL

	PRIMARY KEY(MaHDCT)
	FOREIGN KEY(MaHD) REFERENCES dbo.HOADON(MaHD),
	FOREIGN KEY(MaCTSP) REFERENCES dbo.CHITIETSANPHAM(MaCTSP)
)





select * from MAUSAC
ALTER TABLE dbo.CHITIETSANPHAM
ALTER COLUMN GiamGia FLOAT NULL

select * from SANPHAM where TenSp = N'%Áo len%'
delete from SANPHAM where MaSP != 1 and MaSP != 2 and MaSP != 5 
select * from CHITIETSANPHAM

delete from CHITIETSANPHAM where MaCTSP between 32 and 42 
update CHITIETSANPHAM set SoLuong = 50 , Gia = 200000 where MaCTSP = 7

SELECT * FROM dbo.CHITIETSANPHAM

select * from NHANVIEN

select * from HINHTHUCTHANHTOAN

insert into HINHTHUCTHANHTOAN ( TenHTTT ) 
values (N'Tiền mặt') , 
       (N'Quẹt thẻ') ,
	   (N'Chuyển khoản' )

select * from HOADON
select * from HOADONCHITIET
select * from KHACHHANG


delete from KHACHHANG 
delete from HOADON

